### ISSUE TITLE
Scripts used to build these packages?

### ISSUE THREAD

**Issue by ramsey** [NativePHP/php-bin#2]
Can you share the scripts/workflows used to build these packages? I think these would be really beneficial to the community. Thanks!

**Comment by tben** [comment]
Obviously not the main developer and just speculating but I think it was build with the help of this project.

https://github.com/crazywhalecc/static-php-cli

**Comment by qolarnix** [comment]
+1 please provide build scripts

**Comment by rodber** [comment]
+1 for build scripts.

**Comment by mpociot** [comment]
Yeah indeed, we use https://github.com/crazywhalecc/static-php-cli to build the static binaries 👍

**Comment by DRSDavidSoft** [comment]
@mpociot Wouldn't you prefer to use GitHub actions to build and distribute PHP binaries and avoid pushing exe and dll files to git? That would make more sense.

**Comment by rodber** [comment]
@DRSDavidSoft 

These bin files will fit better on a release package. I found the CI scripts used for building these and I modified to produce `micro` on a tagged release.

https://github.com/rodber/lwmbs/releases/tag/2023.08.02

There are CI builds for micro, micro-cli, and cli. For MacOS, Windows and Linux. Here's the original project: https://github.com/dixyes/lwmbs
